### ISSUE TITLE
I think you did everything right! I will look into this as soon as I can (maybe this weekend).

### ISSUE THREAD

**Issue by LuLing06** [ahwillia/tensortools#14]
_Originally posted by @ahwillia in https://github.com/ahwillia/tensortools/issues/12#issuecomment-417005268_

I also can not install it for the same issue

**Comment by ahwillia** [comment]
The docs are now updated to suggest installing like this:

```
pip install git+https://github.com/ahwillia/tensortools
```

If you encounter more trouble please respond in issue #12 so that the discussion is all in one place.

**Comment by LuLing06** [comment]
When I did 'pip install git+https://github.com/ahwillia/tensortools' in
commend prompt, I got an error message" Error [WinError 2] The system could
not find the specified file。 while executing command git clone -q
https://github.com/ahwillia/tensortools
C:\Users\13120\AppData\Local\Temp\pip-req-build-z4r3wdju Cannot find
command 'git' - do you have 'git' installed and in your PATH?'

Can you tell me how to fix it?

Thanks you
