### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by CellAssembly** [ahwillia/tensortools#16]
Hello,

I installed tensortools and tried running the first example. It give an error at the import statement as below:
File "/home/.conda/envs/myenv/lib/python2.7/site-packages/munkres.py", line 79
    def pad_matrix(self, matrix: Matrix, pad_value: int=0) -> Matrix:

Any thoughts or help is appreciated!

**Comment by CellAssembly** [comment]
Okay, I made a new conda environement with python 3.6 and the error is fixed (I was using 2.7.14 before). Perhaps this helps someone else in the future.

**Comment by ahwillia** [comment]
Yes this indeed looks like a python 2 vs. 3 compatibility issue. I will add a note to the README that Python 3 is required. Thanks for mentioning this!
