### ISSUE TITLE
setup.py no longer compiles (cmdclass not defined)

### ISSUE THREAD

**Issue by BrendanKennedy** [ahwillia/tensortools#21]
Recent changes to setup.py have made installation of package not work. Installation through pip results in "NameError: name 'cmdclass' is not defined". 

I see that the most recent commit (11 days) deleted code that initialized `cmdclass` in setup.py

**Comment by ahwillia** [comment]
Thanks for catching this! I was being sloppy while removing a cython dependency in an effort to simplify things. Should be fixed now (https://github.com/ahwillia/tensortools/commit/cfb411fac9af84102ab84afbee94a1cef5fdddc3) but please re-open if I missed something else...
