### ISSUE TITLE
Tensor constructor

### ISSUE THREAD

**Issue by Daniel0520** [ahwillia/tensortools#22]
Hi,
I am totally beginner in this topic. I'd like to construct a tensor from a 3D array data (with dimension neuron, time, trials). In the examples I found how to generate ktensor from random data with Kronecker product but I am not sure it is the same way I would need for the 3D array->tensor generation.
Could you please provide me an example for this issue?

**Comment by ahwillia** [comment]
See https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html

Here are some quick examples:

```python
# Creates a vector
x = np.array([1, 2, 3, 4, 5])

# Creates a matrix
y = np.array(
  [[1, 2, 3],
   [4, 5, 6]])

 # Creates a tensor
z = np.array([
  [[1, 2, 3],
   [4, 5, 6]],   # first slice.
  
  [[7, 8, 9],
   [10, 11, 12]]  # second slice.
])
```

Also you can create a tensors filled with zeros, random numbers, etc.

```python
a = np.random.randn(4, 5, 6)  # 4 x 5 x 6 tensor
b = np.zeros((4, 5, 6))  # 4 x 5 x 6 tensor
```

Etc. Also see `np.reshape` for turning vectors to matrices to tensors, etc.

**Comment by ahwillia** [comment]
Apologies, just re-read your question and in case you are interested in constructing a `KTensor` see the example below. The `KTensor` stands for "Kruskal Tensor"; it holds the low-dimensional approximation of a tensor into factor matrices. Refer to [Kolda & Bader](https://doi.org/10.1137/07070111X) for background material.

Dense higher-order tensors are just treated as numpy arrays (see my above comment).

```python
import tensortools as tt
import numpy.random as npr

# Create random factor matrices
U = npr.randn(10, 3)  # neuron factors, e.g.
V = npr.randn(11, 3)  # temporal factors, e.g.
W = npr.randn(12, 3)  # trial factors, e.g.

# Create a tensor in Kruskal form
model  = tt.KTensor([U, V, W])

model.rank  # should return 3
model.shape  # should return (10, 11, 12)
model.full()   # creates dense tensor
```

**Comment by Daniel0520** [comment]
Hi, thank you for the explanation. 
1.) As far as I understand your example shows how to construct a 3-rank Kruskal tensor from factors with outer production.
However it is still not completely clear for me how to generate U,V,W factors from a 3D array where the first dimension is the neurons, the second is the Ca curves (as a function of time) and the third one is the Ca curves in different trials.  Do you think there is a code for the decomposition of the 3D array for these factors?
Many thanks in advance, Daniel

**Comment by ahwillia** [comment]
You need to fit the model to a dense 3D array of data. If your data is in an array `X` with dimensions neurons x time x trials, then you can fit a model with 5 components as follows:

```
import tensortools as tt

U = tt.cp_als(X, rank=5, verbose=True)  # fits unconstrained decomposition
V = tt.ncp_hals(X, rank=5, verbose=True)  # fits decomposition with nonnegative factors.
```
