### ISSUE TITLE
Fitting TCA with only certain non-negative dimensions

### ISSUE THREAD

**Issue by klmcguir** [ahwillia/tensortools#24]
We talked about this a while ago, but I think it would be very useful, especially for calcium imaging data, to be able fit TCA forcing only two dimensions to be non-negative while allowing the third to be negative or positive. This might allow you to do things like find components that are modulated by shared inhibition for a group of cells but still make the results more interpretable than cp_als, etc. where you need to keep track of a lot of sign inversions!

Not sure how easy this would be to do!

**Comment by ahwillia** [comment]
Thanks for the reminder! I just added an option for this 304b467c0a404b638db7458d8363c82c152fa016. Haven't tested it extensively so proceed with caution. Compare results with and without the constraint -- I don't anticipate that they should differ that dramatically if only one of the three modes is allowed negative.

That being said I think it would be really interesting to look for inhibition as you describe! Closing this for now, but let me know if you run into trouble.

**Comment by klmcguir** [comment]
You rock! I’ll let you know how testing goes.

Best,
Kelly

**Comment by klmcguir** [comment]
Hi, right now this constraint does not seem to be working. I have not worked out where the trouble is, but right now this seems to be allowing all three modes to be negative even when you pass `negative_modes=[0]` as in the example below (or any other input I have tried so far).

![Screen Shot 2019-11-20 at 9 25 55 AM](https://user-images.githubusercontent.com/25494243/69247551-8bf08c00-0b78-11ea-9ac4-e64870f5f3bf.png)

**Comment by ahwillia** [comment]
Whoops. That was an embarrassing one on my part.

24795f20b108bcc36910e0ba99fcad1ce30e6fc8 fixes this and also adds a test (which I should have done in the first place... lesson learned until next time).

![image](https://user-images.githubusercontent.com/636625/69256789-dc62ec00-0b6e-11ea-8722-26b07e658e80.png)
