### ISSUE TITLE
Reconstruction error

### ISSUE THREAD

**Issue by Daniel0520** [ahwillia/tensortools#27]
Hi Alex,
just a short question: in function plot_objective where the reconstruction error is plotted, is the objective function in percentage or in absolute value?

(congratulation for your toolbox, great work!)
many thanks in advance,
Daniel

**Comment by ahwillia** [comment]
Thanks, the error is computed by: `np.linalg.norm(X - X_est) / np.linalg.norm(X)`

So more or less and R^2 type metric (but there is no mean-centering step).
