### ISSUE TITLE
Tensortools installation failed

### ISSUE THREAD

**Issue by sidazhang** [ahwillia/tensortools#29]
```RuntimeError: cannot cache function '_hals_update': no locator available for file 'miniconda3/lib/python3.7/site-packages/tensortools-0.3-py3.7.egg/tensortools/optimize/ncp_hals.py'```

**Comment by sidazhang** [comment]
Any workarounds? e.g. turn off caching?

I don't need this to be fast. I just need it to work to run some code from a tutorial

**Comment by ahwillia** [comment]
Turning off cacheing should fix this and not result in a big performance hit anyways, so I went ahead and did it... https://github.com/ahwillia/tensortools/commit/af612f95ec1e1bc274c902b1cfa55197f511c609
I can't reproduce the error on my end, I think it must be something about different versions of numba or how numba is set up on your machine (see https://github.com/numba/numba/issues/4032)

Let me know if the problem persists.

**Comment by sidazhang** [comment]
Yep this was it
